name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: Actions
          uses: actions/checkout@v7

        - name: Welcome message
          run: |
            echo "Welcome to my firt workflow"
            ls -ltrh
            cat README.md

        - name: Cowsay message
          run: cowsay -f dragon "Run for cover...... I'm dragon .... Rawrrrrrrr" >> dragon.txt
