name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: Actions
          uses: actions/checkout@v7
          
        - name: Welcome message
          run: echo "Welcome to my firt workflow"

        - name: list files
          run: ls

        - name: read file
          run: cat README.md
